#!/usr/bin/env bash
set -euo pipefail

# RRL-IMPL executable-example acceptance (ruff-12). Every live rule's documented example is not
# decoration: it is *run* against the real product. Sourced from the registry (`explain CODE --json`,
# the one metadata object the docs are also generated from, `notes/01-schema.md` §8), the harness
# proves for each rule with examples that:
#   - the `bad` snippet, run through the exact frontend, reports exactly that rule (no more, no less,
#     no infrastructure failure);
#   - a fixable rule's `fix` rewrites `bad` into its `good` byte-for-byte, and a re-check is silent
#     (the fix is idempotent);
#   - a report-only rule's `good` (when shown) is itself clean for that rule.
# It also pins the CLI lifecycle contract (`explain` on a live / retired / meta / unknown code) and
# the generated-docs drift check (`docs --check`), so a metadata edit that forgets to regenerate the
# pages fails here.
#
# Snippets omit the private-module `module` header for readability; the whole project is module-system
# so the harness prepends it before running. Preview/deprecated rules are unlocked with `--preview`,
# exactly the gate a user hits. Every example goes through the exact frontend (artifact and module
# evidence disabled), the only path that projects a syntax rule and elaborates a semantic one, matching
# tests/syntax/run.sh and tests/semantic/run.sh.

repo_root=$(cd "$(dirname "$0")/../.." && pwd)
work=$(mktemp -d)
cache_root="$repo_root/.lean-fmt-cache"
# `fix` writes in place under the project root, so example probes are in-tree; the trap clears them
# and the cache even if a case fails mid-run.
trap 'rm -rf "$work" "$cache_root" "$repo_root"/tests/catalog/.probe-*.lean' EXIT

cd "$repo_root"
rm -rf "$cache_root"
LEAN_NUM_THREADS=1 lake build lean-fmt
application=$(lake -q query lean-fmt --text)

# The registry dumps: the full catalog and one detailed record per code. Generated by the product, so
# the harness never re-encodes any rule fact.
env "$application" rules --json >"$work/rules.json"

python3 - "$application" "$work" "$repo_root" <<'PY'
import json, os, subprocess, sys

application, work, repo_root = sys.argv[1], sys.argv[2], sys.argv[3]
catalog_dir = os.path.join(repo_root, "tests", "catalog")

def run(args, expect):
    env = dict(os.environ)
    env["LEAN_FMT_DISABLE_ARTIFACT"] = "1"
    env["LEAN_FMT_TEST_DISABLE_MODULE_EVIDENCE"] = "1"
    p = subprocess.run([application] + args, capture_output=True, text=True, env=env)
    if p.returncode != expect:
        sys.stderr.write(f"expected exit {expect}, got {p.returncode} for: {' '.join(args)}\n")
        sys.stderr.write(p.stdout + "\n" + p.stderr + "\n")
        sys.exit(1)
    return p

def explain(code):
    p = subprocess.run([application, "explain", code, "--json"], capture_output=True, text=True)
    if p.returncode != 0:
        sys.stderr.write(f"explain {code} --json failed: {p.stderr}\n")
        sys.exit(1)
    return json.loads(p.stdout)

def wrap(body):
    # A snippet becomes a module-system source: `module` header, one trailing newline.
    return "module\n" + body.rstrip("\n") + "\n"

rules = json.load(open(os.path.join(work, "rules.json")))
exempt = {"FMT003", "FMT004", "FMT006"}  # findings not expressible as a self-contained snippet (§10)
tested = 0

for rule in sorted(rules, key=lambda r: r["code"]):
    code = rule["code"]
    info = explain(code)
    examples = info["examples"]
    stable = info["lifecycle"] == "stable"
    preview = [] if stable else ["--preview"]

    if code in exempt:
        assert not examples, f"{code}: example-exempt rule must carry no example, got {examples}"
        continue
    assert examples, f"{code}: live non-exempt rule has no executable example"

    for i, ex in enumerate(examples):
        tag = f"{code}-{i}"
        probe = os.path.join(catalog_dir, f".probe-{tag}.lean")
        rel = os.path.relpath(probe, repo_root)
        with open(probe, "w") as fh:
            fh.write(wrap(ex["bad"]))

        # The `bad` snippet reports exactly this rule and nothing else.
        p = run(["check", "--root", ".", "--json", "--no-cache"] + preview
                + ["--select", code, rel], expect=1)
        data = json.loads(p.stdout)
        assert len(data["files"]) == 1, (tag, data["files"])
        got = [f["code"] for f in data["files"][0]["findings"]]
        assert got == [code], f"{tag}: bad example reported {got}, expected [{code}]"
        assert data["infrastructureFailures"] == [], (tag, data["infrastructureFailures"])
        assert data["broken"] == 0, (tag, "bad example did not parse/elaborate", data)

        good = ex.get("good")
        if good is None:
            os.remove(probe)
            tested += 1
            continue

        if info["fixable"]:
            # `fix` rewrites `bad` into `good`, byte-for-byte after the shared `module` wrap.
            # `--unsafe-fixes` admits both safe and unsafe fixes, so an example's `good` is the fully
            # fixed form regardless of the rule's applicability (FMT014's rename is unsafe; FMT013's
            # paren deletion is safe — both reach their documented `good` here).
            run(["fix", "--root", ".", "--json", "--no-cache", "--unsafe-fixes"] + preview
                + ["--select", code, rel], expect=0)
            produced = open(probe).read()
            assert produced == wrap(good), (
                f"{tag}: fix output != good example\n--- produced ---\n{produced!r}\n"
                f"--- expected ---\n{wrap(good)!r}")
            # Idempotent: a re-check of the written file is silent for this rule.
            p = run(["check", "--root", ".", "--json", "--no-cache"] + preview
                    + ["--select", code, rel], expect=0)
            assert json.loads(p.stdout)["findings"] == 0, (tag, "fix not idempotent")
        else:
            # A report-only rule may still *show* the corrected form; it must itself be clean.
            with open(probe, "w") as fh:
                fh.write(wrap(good))
            p = run(["check", "--root", ".", "--json", "--no-cache"] + preview
                    + ["--select", code, rel], expect=0)
            got = [f["code"] for f in json.loads(p.stdout)["files"][0]["findings"]]
            assert got == [], f"{tag}: good example still reports {got}"
        os.remove(probe)
        tested += 1

print(f"executed {tested} registry examples across {len(rules)} live rules")
PY

# --- CLI lifecycle contract: `explain` across the code classes ------------------------------------
# `explain` answers for every class of code the product can print (`notes/01-schema.md` §8): a live
# rule explains with exit 0; a retired code explains its reserved-table disposition (exit 0) though it
# names no live rule; a meta self-diagnostic (FMT900/FMT901) explains its description (exit 0) though
# it is in neither table, because it is never selectable. Only a code the product could never have
# emitted is an error — FMT999, never assigned, exit 2.
#
# FMT900 used to be in that error class (`ruff-12b`). It was wrong: a user meets FMT900 by reading it
# in a report, and `unknown rule: FMT900` denies a code the product had just printed. Absence from the
# registry is a fact about *selection*, not about existence. This is the graceful-degradation surface
# a stale config/selector lands on, and denying a live code is not graceful.
explain_expect() {
  local code=$1 expect=$2 needle=$3
  set +e
  out=$(env "$application" explain "$code" 2>&1)
  actual=$?
  set -e
  if [[ $actual -ne $expect ]]; then
    printf 'explain %s: expected exit %s, got %s\n%s\n' "$code" "$expect" "$actual" "$out" >&2
    exit 1
  fi
  if [[ -n $needle && $out != *"$needle"* ]]; then
    printf 'explain %s: output missing %q\n%s\n' "$code" "$needle" "$out" >&2
    exit 1
  fi
}
explain_expect FMT003 0 "FMT003"
explain_expect FMT001 0 "retired"
explain_expect FMT900 0 "suppressed nothing"
explain_expect FMT901 0 "does not parse as a directive"
explain_expect FMT999 2 ""

# --- Generated-docs drift: the pages regenerate identically from the registry --------------------
env "$application" docs --check >/dev/null

# --- Documentation link check (RRL-FINAL): every relative link in the generated tree resolves, every
# live rule has a page, and the index links each one. Catches a page/link that names a file the
# generator did not write (a dangling doc reference).
env "$application" rules --json >"$work/rules2.json"
python3 - "$repo_root/docs/rules" "$work/rules2.json" <<'PY'
import json, os, re, sys
docs_dir, rules_json = sys.argv[1], sys.argv[2]
codes = [r["code"] for r in json.load(open(rules_json))]
index = open(os.path.join(docs_dir, "index.md")).read()
# Every relative markdown link target in the index exists on disk.
for target in re.findall(r"\]\(([^)]+)\)", index):
    if target.startswith(("http://", "https://", "#")):
        continue
    assert os.path.exists(os.path.join(docs_dir, target)), f"index links a missing file: {target}"
# Every live rule has a page and the index links it.
for code in codes:
    assert os.path.exists(os.path.join(docs_dir, f"{code}.md")), f"no page for live rule {code}"
    assert f"({code}.md)" in index, f"index does not link {code}"
# The generated config schema is referenced and present.
assert os.path.exists(os.path.join(docs_dir, "schema.json")), "schema.json missing"
assert "schema.json" in index, "index does not mention schema.json"
print(f"doc links OK: {len(codes)} rule pages, index + schema resolve")
PY

echo "lean-fmt catalog executable-example tests passed"
